# Generated by Django 4.2.2 on 2023-07-14 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'content_type', 'object_id')},
        ),
    ]
